FROM gradle:7.0-jdk11 AS build

WORKDIR /home/gradle/src

# Only copy dependency-related files
COPY build.gradle.kts settings.gradle.kts /home/gradle/src/

# Only download dependencies
# Eat the expected build failure since no source code has been copied yet
RUN gradle clean build --no-daemon > /dev/null 2>&1 || true

# Copy all files
COPY ./ /home/gradle/src/

EXPOSE 8080

# Run the app
RUN gradle bootRun
