version: "3"

services:
  db:
    container_name: ubicardb
    image: postgres:13-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ubicar
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
