spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5431/ubicar
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  # Pretty-print JSON responses
  jackson:
    serialization:
      indent_output: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/ubicar-3872e
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

