spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/ubicar
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  servlet:
    multipart:
      max-file-size: 128KB
#      max-request-size: 128KB


  # Pretty-print JSON responses
  jackson:
    serialization:
      indent_output: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/ubicar-3872e
          jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com

