spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5431/ubicar
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  # Pretty-print JSON responses
  jackson:
    serialization:
      indent_output: true
